const CONFIG = {
    introTitle: 'Bảo nhể quê 1 cục',
    introDesc: `Thg quê một cục lấy ci che mặt lại đi.Sai là sập nguồn 15p' nhá `,
    btnIntro: 'Nhanh đi conchos',
    title: 'nhanh nhanh cái tay lên',
    desc: 'Tối bao anh đi ăn chè ',
    btnYes: 'okiiii luôn',
    btnNo: 'Deo :3',
    question:'Tối deo bao làm chó nhá',
    btnReply: 'Gửi cho anh hưng đtr',
    reply: 'Oki.Bao m cả bim bim',
    mess: 'T biết m tốt bụng mà.Camon nhá',
    messDesc: 'Tối 8h30 ở cây ngô đồng nha.',
    btnAccept: 'Okiiiii lun ',
   }
